/**
 * Keywords and patterns used by the emotional moment detector.
 */

export const EMOTION_KEYWORDS: Record<string, string> = {
  //# Triste
  'triste': 'Triste',
  'tristeza': 'Triste',
  'llorar': 'Triste',
  'lloro': 'Triste',
  'pena': 'Triste',
  'apenada': 'Triste',
  'apenado': 'Triste',
  'terrible': 'Triste',
  'deprimido': 'Triste',
  'deprimida': 'Triste',
  'me dio pena': 'Triste',
  'me dolió': 'Triste',
  'tengo ganas de llorar': 'Triste',
  'me dieron ganas de llorar': 'Triste',
  'lloré': 'Triste',

  //# Ansioso/a

  'ansioso': 'Ansioso/a',
  'ansiosa': 'Ansioso/a',
  'ansiedad': 'Ansioso/a',
  'nervioso': 'Ansioso/a',
  'nerviosa': 'Ansioso/a',
  'angustia': 'Ansioso/a',
  'angustiado': 'Ansioso/a',
  'angustiada': 'Ansioso/a',
  'miedo': 'Ansioso/a',
  'preocupado': 'Ansioso/a',
  'preocupada': 'Ansioso/a',
  'preocupación': 'Ansioso/a',
  'inseguro': 'Ansioso/a',
  'insegura': 'Ansioso/a',
  'asustada': 'Ansioso/a',
  'asustado': 'Ansioso/a',
  'temor': 'Ansioso/a',
  'me dio miedo': 'Ansioso/a',
  'me dio ansiedad': 'Ansioso/a',
  'me dio angustia': 'Ansioso/a',
  'me angustió': 'Ansioso/a',
  'me preocupó': 'Ansioso/a',
  'me dio vueltas': 'Ansioso/a',
  'no puedo dejar de pensar': 'Ansioso/a',
  'tengo un nudo': 'Ansioso/a',
  'tengo presión en el pecho': 'Ansioso/a',

  //# Inquieto/a

  'frustrado': 'Inquieto/a',
  'frustrada': 'Inquieto/a',
  'frustración': 'Inquieto/a',
  'enojado': 'Inquieto/a',
  'enojada': 'Inquieto/a',
  'enojo': 'Inquieto/a',
  'enfado': 'Inquieto/a',
  'enfadado': 'Inquieto/a',
  'enfadada': 'Inquieto/a',
  'irritado': 'Inquieto/a',
  'irritada': 'Inquieto/a',
  'irritación': 'Inquieto/a',
  'rabia': 'Inquieto/a',
  'ira': 'Inquieto/a',
  'molesto': 'Inquieto/a',
  'molesta': 'Inquieto/a',
  'harto': 'Inquieto/a',
  'harta': 'Inquieto/a',
  'impotencia': 'Inquieto/a',
  'agobio': 'Inquieto/a',
  'agobiado': 'Inquieto/a',
  'agobiada': 'Inquieto/a',
  'estresado': 'Inquieto/a',
  'estresada': 'Inquieto/a',
  'estrés': 'Inquieto/a',
  'abrumado': 'Inquieto/a',
  'abrumada': 'Inquieto/a',
  'confundido': 'Inquieto/a',
  'confundida': 'Inquieto/a',
  'colapsada': 'Inquieto/a',
  'colapsado': 'Inquieto/a',
  'saturada': 'Inquieto/a',
  'saturado': 'Inquieto/a',
  'perdida': 'Inquieto/a',
  'perdido': 'Inquieto/a',
  'bloqueada': 'Inquieto/a',
  'bloqueado': 'Inquieto/a',
  'desbordada': 'Inquieto/a',
  'desbordado': 'Inquieto/a',
  'sensible': 'Inquieto/a',
  'me siento rara': 'Inquieto/a',
  'me siento raro': 'Inquieto/a',
  'me dejó pensando': 'Inquieto/a',
  'me molestó': 'Inquieto/a',
  'me frustró': 'Inquieto/a',
  'me superó': 'Inquieto/a',
  'me sobrepasó': 'Inquieto/a',
  'me colapsó': 'Inquieto/a',
  'no sé qué siento': 'Inquieto/a',
  'no entiendo lo que siento': 'Inquieto/a',
  'no sé por qué me siento así': 'Inquieto/a',
  'me dio rabia': 'Inquieto/a',

  //# Un poco bajo/a

  'solo': 'Un poco bajo/a',
  'sola': 'Un poco bajo/a',
  'soledad': 'Un poco bajo/a',
  'vacío': 'Un poco bajo/a',
  'vacía': 'Un poco bajo/a',
  'culpa': 'Un poco bajo/a',
  'culpable': 'Un poco bajo/a',
  'desanimado': 'Un poco bajo/a',
  'desanimada': 'Un poco bajo/a',
  'mal': 'Un poco bajo/a',
  'fatal': 'Un poco bajo/a',
  'decaída': 'Un poco bajo/a',
  'decaído': 'Un poco bajo/a',
  'bajoneada': 'Un poco bajo/a',
  'bajoneado': 'Un poco bajo/a',
  'vergüenza': 'Un poco bajo/a',
  'avergonzada': 'Un poco bajo/a',
  'avergonzado': 'Un poco bajo/a',
  'me siento mal': 'Un poco bajo/a',
  'me siento vacía': 'Un poco bajo/a',
  'me siento vacío': 'Un poco bajo/a',
  'me siento sola': 'Un poco bajo/a',
  'me siento solo': 'Un poco bajo/a',
  'me dejó mal': 'Un poco bajo/a',
  'me afectó': 'Un poco bajo/a',

  //# Cansado/a

  'agotado': 'Cansado/a',
  'agotada': 'Cansado/a',
  'cansado': 'Cansado/a',
  'cansada': 'Cansado/a',
  'cansancio': 'Cansado/a',
  'agotamiento': 'Cansado/a',
  'desmotivado': 'Cansado/a',
  'desmotivada': 'Cansado/a',
  'me cansó': 'Cansado/a',
  'me agotó': 'Cansado/a',

  //# Feliz

  'feliz': 'Feliz',
  'felicidad': 'Feliz',
  'contento': 'Feliz',
  'contenta': 'Feliz',
  'alegría': 'Feliz',
  'alegre': 'Feliz',
  'agradecido': 'Feliz',
  'agradecida': 'Feliz',
  'emocionada': 'Feliz',
  'emocionado': 'Feliz',
  'motivada': 'Feliz',
  'motivado': 'Feliz',
  'orgullosa': 'Feliz',
  'orgulloso': 'Feliz',

  //# En calma

  'tranquilo': 'En calma',
  'tranquila': 'En calma',
  'en paz': 'En calma',
  'esperanza': 'En calma',
  'bien': 'En calma',
  'calmada': 'En calma',
  'calmado': 'En calma',
  'aliviada': 'En calma',
  'aliviado': 'En calma',
  'esperanzada': 'En calma',
  'esperanzado': 'En calma',
  'calma': 'En calma',
};

export const CAUSE_PATTERNS: string[] = [
  'porque', 'por culpa', 'debido a', 'me pasó', 'me pasa',
  'el trabajo', 'mi trabajo', 'en el trabajo', 'en la oficina',
  'mi jefe', 'con mi jefe', 'los compañeros', 'mis compañeros',
  'con mi pareja', 'el ambiente', 'ambiente laboral',
  'con mi familia', 'con mi mamá', 'con mi papá', 'con mi hermano',
  'con mi hermana', 'con mi hijo', 'con mi hija', 'con mis amigos',
  'hoy me', 'ayer me', 'nos peleamos', 'me dijo que', 'me hizo sentir',
  'la relación', 'el dinero', 'la plata', 'las deudas', 'la universidad',
  'el estudio', 'los exámenes', 'la escuela', 'el colegio',
  'mi salud', 'el médico', 'el doctor', 'la casa', 'mi casa',
  'trabajo', 'pega', 'jefa', 'jefe', 'compañero', 'compañera',
  'equipo', 'oficina', 'reunión', 'cliente', 'clientes', 'correo', 'correos',
  'jornada', 'carga laboral', 'ambiente laboral', 'presión laboral', 'tarea',
  'tareas', 'responsabilidad', 'responsabilidades', 'sueldo', 'renunciar',
  'cambiarme de trabajo', 'burnout', 'me exigen', 'me pidieron', 'me retaron',
  'me criticaron', 'no me valoran', 'no reconocen mi trabajo',
  'familia', 'mamá', 'papá', 'hermana', 'hermano', 'hijo', 'hija',
  'pareja', 'pololo', 'polola', 'marido', 'esposo', 'esposa', 'casa',
  'discusión familiar', 'problema familiar', 'me preocupa mi familia',
  'relación', 'pololo', 'polola', 'marido', 'esposo', 'esposa', 'discusión',
  'pelea', 'distancia', 'celos', 'me sentí ignorada', 'me sentí ignorado',
  'me sentí poco querida', 'me sentí poco querido', 'me sentí poco escuchada',
  'me sentí poco escuchado', 'salud', 'cuerpo', 'dolor', 'me duele', 'cansancio',
  'agotamiento', 'sueño', 'dormir', 'dormí mal', 'no dormí', 'insomnio',
  'ansiedad física', 'presión en el pecho', 'nudo en la garganta',
  'dolor de cabeza', 'dolor de espalda', 'malestar',
  'dinero', 'deuda', 'deudas', 'pago', 'pagos', 'sueldo', 'cuentas',
  'gastos', 'arriendo', 'finanzas', 'estabilidad', 'me preocupa la plata',
  'no me alcanza', 'tengo miedo de no poder pagar',
];

export const CONSEQUENCE_PATTERNS: string[] = [
  'no puedo dormir', 'no duermo', 'no como', 'no quiero comer',
  'lloro', 'me paralizo', 'exploto', 'me alejo', 'me aíslo',
  'me cuesta concentrar', 'no me concentro', 'me duele',
  'no tengo energía', 'no tengo ganas', 'no quiero hacer nada',
  'me afecta', 'me está afectando', 'he llorado', 'me quebré',
  'me sentí vulnerable', 'me sentí invisible', 'me sentí poco valorada',
  'me sentí poco valorado', 'me sentí juzgada', 'me sentí juzgado',
  'me sentí rechazada', 'me sentí rechazado', 'me sentí sola',
  'me sentí solo', 'me hace sentir', 'me deja mal '
];

export const PATTERN_KEYWORDS: string[] = [
  'siempre que', 'cada vez que', 'últimamente', 'otra vez',
  'como siempre', 'me pasa seguido', 'es la tercera vez',
  'de nuevo', 'todo el tiempo', 'nunca cambia', 'sigue pasando',
  'ya no sé qué hacer', 'ya estoy harto', 'ya estoy harta',
  'siempre es lo mismo', 'siempre pasa', 'no es la primera vez',
];

export const FAREWELL_PATTERNS: string[] = [
  'chao', 'me voy', 'gracias por escuchar', 'hablamos',
  'nos vemos', 'hasta luego', 'bye', 'adiós', 'adios',
  'buenas noches', 'hablamos después', 'te cuento luego',
  'me tengo que ir', 'ya me voy', 'hasta mañana',
  'cuídate', 'gracias gaia', 'eso era todo', 'era eso',
  'me iré a dormir', 'me voy a dormir', 'voy a dormir',
  'no quiero seguir escribiendo', 'no quiero hablar más',
  'quiero descansar', 'necesito descansar', 'voy a descansar',
  'gracias', 'muchas gracias', 'eso era', 'eso sería', 'eso es todo',
  'por ahora eso', 'por ahora nada más', 'listo', 'ok gracias', 'bueno gracias',
  'me voy a dormir', 'mañana seguimos', 'seguimos mañana', 'hoy no quiero hablar más',
  'ya me siento mejor', 'me ayudó hablarlo', 'me hizo bien hablarlo',
  'cerramos por hoy', 'terminemos por hoy', 'hasta mañana', 'buenas noches',
];

export const DONT_SAVE_KEYWORDS: string[] = [
  'hola',
  'buenos días',
  'buenas tardes',
  'buenas noches',
  'qué haces',
  'ayúdame',
  'explícame',
  'quiero saber',
  'tengo una duda',
  'cómo funciona',
  'qué significa',
  'dame una idea',
  'hazme un resumen',
  'ordena esto',
  'necesito ayuda con una tarea',
];

export const INTENSIFIERS_KEYWORDS: string[] = [
  'mucho',
  'demasiado',
  'bastante',
  'muy',
  'horrible',
  'terrible',
  'fuerte',
  'intenso',
  'intensa',
  'pesado',
  'pesada',
  'agotador',
  'agotadora',
  'difícil',
  'duro',
  'dura',
  'insoportable',
  'no puedo más',
  'ya no puedo',
  'me supera',
  'me sobrepasa',
  'me cuesta',
  'me cuesta mucho',
  'me tiene mal',
  'me tiene cansada',
  'me tiene cansado',
  'me tiene agotada',
  'me tiene agotado'
];